### ISSUE TITLE
MVP1: List all Pokemon

### ISSUE THREAD

**Issue by prostodevs** [BrandonCope/Pokemon_Team_Builder#1]
- [x] Grid layout for landing page
- [x] Clickable snippet link (linked to details page)
- [x] Home button to return to landing page (navigation bar)

- [x] See MVP1:
"https://github.com/BrandonCope/Pokemon_Team_Builder/wiki/User-Stories"

**Comment by ramyashreeshetty** [comment]
hey, I went through the project. So just wanted to ensure that is someone working on this.

**Comment by BrandonCope** [comment]
> hey, I went through the project. So just wanted to ensure that is someone working on this.

Yeah stay tuned, will be complete later this week.

**Comment by ramyashreeshetty** [comment]
oh! so contributions are closed?

**Comment by BrandonCope** [comment]
> oh! so contributions are closed?

Yeah it is for now, sorry. Small team project. Current tasks are already assigned.
